name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  go-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  # https://golangci-lint.run/usage/quick-start/
  # github action: https://golangci-lint.run/usage/install#github-actions
  go-linter:
    name: lint
    runs-on: ubuntu-latest
    needs: [go-build-and-test]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          # see https://github.com/golangci/golangci-lint/releases
          version: v1.55.2
          args: --timeout=5m

  # https://securego.io/
  # https://github.com/securego/gosec
  go-security:
    name: gosec
    runs-on: ubuntu-latest
    needs: [go-build-and-test]
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  # Vulnerability Management for Go
  # https://go.dev/blog/vuln
  # Full documentation: https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
  go-vulncheck:
    name: "Govulncheck"
    runs-on: ubuntu-latest
    needs: [go-build-and-test]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5

      - name: Get govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash

      - name: Run govulncheck
        run: govulncheck ./...
        shell: bash
